spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true  # Ativa a descoberta de servi√ßos no Eureka
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service  # 'lb://' faz o gateway buscar no Eureka, lb significa load balancer
          predicates:
            - Path=/login/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka  # A URL do Eureka
#      defaultZone: http://eureka:8761/eureka/
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
